# Generated by Django 2.2.17 on 2020-11-24 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads_Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('founder', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_clients_account', to=settings.AUTH_USER_MODEL)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ads_Client_Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('ads_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_channels', to='DatabaseApi.Ads_Client')),
            ],
        ),
        migrations.CreateModel(
            name='Ads_Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('duration', models.BigIntegerField(default=0)),
                ('ads_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='DatabaseApi.Ads_Client')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('founder', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('logo_left', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('logo_right', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('ticker', models.CharField(blank=True, max_length=1000)),
                ('ticker_interval', models.BigIntegerField(default=0)),
                ('reload_time', models.BigIntegerField(default=0)),
                ('orientation', models.IntegerField(choices=[(0, 'Горизонтальная'), (1, 'Вертикальная')], default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('founder', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('last_online', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices_account', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='DatabaseApi.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('duration', models.BigIntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='DatabaseApi.Content')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'user'), (1, 'client')], default=1)),
                ('red', models.PositiveSmallIntegerField(default=108)),
                ('green', models.PositiveSmallIntegerField(default=117)),
                ('blue', models.PositiveSmallIntegerField(default=125)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Showed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('all_time', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField(default=0)),
                ('update_year', models.DateTimeField()),
                ('month', models.PositiveIntegerField(default=0)),
                ('update_month', models.DateTimeField()),
                ('week', models.PositiveIntegerField(default=0)),
                ('update_week', models.DateTimeField()),
                ('day', models.PositiveIntegerField(default=0)),
                ('update_day', models.DateTimeField()),
                ('last_time', models.DateTimeField(blank=True)),
                ('next_time', models.DateTimeField(blank=True)),
                ('ads_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='DatabaseApi.Ads_Video')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseApi.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_field', models.DateTimeField(auto_now=True)),
                ('ads_client_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='DatabaseApi.Ads_Client_Channel')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='DatabaseApi.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='DatabaseApi.Device')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='contents',
            field=models.ManyToManyField(blank=True, related_name='channels', to='DatabaseApi.Content'),
        ),
        migrations.AddField(
            model_name='channel',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='channels_worker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ads_client_channel',
            name='ads_videos',
            field=models.ManyToManyField(blank=True, to='DatabaseApi.Ads_Video'),
        ),
        migrations.AddField(
            model_name='ads_client_channel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_clients', to='DatabaseApi.Channel'),
        ),
    ]
