# Generated by Django 2.2.17 on 2020-11-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_online',
            field=models.DateTimeField(),
        ),
    ]
