# Generated by Django 2.2.17 on 2020-12-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApi', '0002_auto_20201125_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads_client_channel',
            name='interval',
            field=models.BigIntegerField(default=0),
        ),
    ]
